---
service: rekognition-poc

provider:
  name: aws
  runtime: nodejs12.x
  defaultStage: ${env:MYDAIR_LOCAL_STAGE}
  stage: ${opt:stage, self:provider.defaultStage}
  region: ${opt:region, 'eu-west-1'}
